name: CI - VerifiAI (Next.js)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout your code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # change if you use a different version

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Optional: Lint your code
      - name: Run Linter
        run: npm run lint

      # Step 4: Build the Next.js app
      - name: Build the project
        run: npm run build

      # Step 5: Run tests (if you have tests)
      - name: Run tests
        run: npm run test
